### ISSUE TITLE
windows 32   (\"Error parsing document : 0\"), no element found, 1, 1, 0"

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/WinRPM.jl#104]
Intermittently showing up on HDF5
```
INFO: Building Blosc
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/a3074cbaabd22a9af6edc1f68c3d3c79f030c6dbe35803028f9994bfdace391b-primary.xml.gz
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/1bb4d3f1ed96a7ad1efd94bc21b8825e0cff500871e571626f385f898bcbfffd-primary.xml.gz
WARNING: encounted invalid data while parsing repomd
===============================[ ERROR: WinRPM ]================================
LoadError: "ErrorException(\"Error parsing document : 0\"), no element found, 1, 1, 0"
while loading C:\Users\appveyor\.julia\v0.5\WinRPM\deps\build.jl, in expression starting on line 2
================================================================================
================================[ BUILD ERRORS ]================================
WARNING: WinRPM had build errors.

```

**Comment by musm** [comment]
I really wish gallium was working so I could try and debug this

**Comment by robertdj** [comment]
@musm: Have you found a solution? The error 

> LoadError: "ErrorException(\"Error parsing document : 0\"), no element found, 1, 1, 0"

occurs when parsing the XML file `INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml`
It's weird because this error only turned up recently for me. Maybe the file was changed at some point?

**Comment by musm** [comment]
@robertdj  maybe try to delete the `cache` folder in `<userfolder>\.julia\v0.6\WinRPM`and run `WinRPM.build()` long shot but worth a try

**Comment by robertdj** [comment]
Your suggestion didn't work, but it inspired me to delete the entire `~\.julia` directory -- and that worked :-)

**Comment by musm** [comment]
ideally we should figure out the problem as deleting the entire `~\.julia` is  a terrible recommendation, but glad it worked.

**Comment by robertdj** [comment]
I completely agree! But after such a long time I'm glad to found *some* way.

**Comment by musm** [comment]
Is there reproducible case for this bug? I seem to only get it intermittently

**Comment by robertdj** [comment]
I haven't had any problems after my last update. But then again, I haven't tried to provoke it :-)

**Comment by musm** [comment]
issue stale
