### ISSUE TITLE
Unknown download failure, error code: 2148270086

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPackaging/WinRPM.jl#107]
Julia v0.5, Windows 10 64-bit.

```julia
julia> using WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download

julia> WinRPM.update()
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml

julia> WinRPM.update()
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
WARNING: received error 0 while downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_42.2/repodata/repomd.xml
```

**Comment by ChrisRackauckas** [comment]
It seems like AppVeyor is having this issue as well. Digging up some of my CI results:

https://ci.appveyor.com/project/ChrisRackauckas/stochasticdiffeq-jl/build/1.0.208/job/b4w7y1htyg57o4bm#L188

It looks like RMath and HDF5 has been failing to build on AppVeyor ever since the link change by @staticfloat's set of PRs, and these throw the same error code. I don't understand the error enough to know if it's actually related, or if it's a coincidence that should be another issue.

**Comment by staticfloat** [comment]
What is the mechanism that WinRPM uses to download files?

Note that these downloads are independent of what we did; we changed how Julia itself is downloaded, it shouldn't have any difference on how WinRPM downloads stuff, unless WinRPM is using powershell to download, and thereby is inheriting the TLS setting we applied that enables TLS 1.2+.

**Comment by tkelman** [comment]
this flaky thing https://github.com/JuliaPackaging/WinRPM.jl/blob/622b69ac7c57ce815c31431529a1184e175c230c/src/WinRPM.jl#L53-L71

unless removing the cache.julialang.org prefix from sources.list helps, this is upstream of us, opensuse's servers are being unreliable again

**Comment by pfitzseb** [comment]
This is a `INET_E_OBJECT_NOT_FOUND` error, which totally makes sense since there's nothing at those URLs.

**Comment by ChrisRackauckas** [comment]
>Note that these downloads are independent of what we did; we changed how Julia itself is downloaded, it shouldn't have any difference on how WinRPM downloads stuff, unless WinRPM is using powershell to download, and thereby is inheriting the TLS setting we applied that enables TLS 1.2+.

Hmm, it may not be related and just very coincidental. This testing history:

https://ci.appveyor.com/project/ChrisRackauckas/diffeqproblemlibrary-jl/history

shows that the PR with the link change actually passed, but the one right after it had the build issue. It seems they might have coincided at approximately the same time, but are probably orthogonal then (if AppVeyor downloaded using the cached links when it ran the build for the PR (pre-merge). Is there a way to double-check that and make sure?

**Comment by tkelman** [comment]
Oh, they changed the naming. It's not http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_42.2 any more, it's http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2 now.

**Comment by tkelman** [comment]
Try https://github.com/JuliaPackaging/WinRPM.jl/pull/108

**Comment by ChrisRackauckas** [comment]
With #108:

```julia
julia> using WinRPM

julia> WinRPM.update()
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
```

And then the original test which found this from https://github.com/JuliaLang/IJulia.jl/issues/546#issuecomment-303773181:

```julia
julia> Pkg.build("IJulia")
INFO: Building Conda
INFO: Building MbedTLS
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building ZMQ
WARNING: BinDeps.shlib_ext is deprecated.
  likely near C:\Users\Chris\.julia\v0.6\ZMQ\deps\build.jl:22
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
INFO: Found Jupyter version 4.3.0: C:\Users\Chris\.julia\v0.6\Conda\deps\usr\Scripts\jupyter
Writing IJulia kernelspec to C:\Users\Chris\.julia\v0.6\IJulia\deps\julia-0.6\kernel.json ...
Installing julia kernelspec julia-0.6
[InstallKernelSpec] Removing existing kernelspec in C:\Users\Chris\AppData\Roaming\jupyter\kernels\julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in C:\Users\Chris\AppData\Roaming\jupyter\kernels\julia-0.6
```

Looks like #108 works well.

**Comment by lobingera** [comment]
What is now the status of this? afaiu #108 has been merged in to 0.2.5, but i see the same error on Win32 dependencies on appveyor like here: https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/build/1.0.121/job/fjy2gap4mt0hqhj7
@tkelman @ChrisRackauckas

**Comment by tkelman** [comment]
looks like it failed 4 times but succeeded the 5th in that log? sometimes the downloads are flaky

**Comment by lobingera** [comment]
https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/build/1.0.121/job/is97po5huto6t38b
and
https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/build/1.0.121/job/dnogcc1gfdpkj2wa
?

**Comment by tkelman** [comment]
those looks like they downloaded fine but something failed with loading the library, almost certainly a separate issue

**Comment by lobingera** [comment]
Tend to agree. But how to debug? WinRPM says complete, BinDeps reports LoadError: Provider WinRPM.RPM failed to satisfy dependency cairo

**Comment by tkelman** [comment]
Not in this issue. It's not a problem with this package either if the downloading worked. Try dlopening the library on a local install.

**Comment by lobingera** [comment]
Just in case i haven't mentioned this before: I don't have a Win32 system available...

**Comment by tkelman** [comment]
> Not in this issue

appveyor allows you to remotely log in to a build worker

**Comment by lobingera** [comment]
Nice. I'm browsing https://www.appveyor.com/docs/ can you give me a pointer?

**Comment by ChrisRackauckas** [comment]
This seems fixed.
