### ISSUE TITLE
ERROR: failed to download runtime

### ISSUE THREAD

**Issue by eunjongkim** [JuliaPackaging/WinRPM.jl#118]
I see the following error messages when I try to install runtime using WinRPM. Do you have any idea how this issue can be resolved? It happens both in Julia v0.5 and v0.6

julia> WinRPM.install("runtime")
INFO: Multiple package candidates found for mingw64-unistd-pthread-devel, picking newest.
INFO: Packages to update:  runtime
Continue with updates [y/N]? y
INFO: Downloading: runtime
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm
WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm
INFO: try running WinRPM.update() and retrying the install
ERROR: failed to download runtime 0 from https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/noarch/mingw64-runtime-5.0.2-2.24.noarch.rpm.
Stacktrace:
 [1] do_install(::WinRPM.Package) at C:\Users\ekim7\.julia\v0.6\WinRPM\src\WinRPM.jl:456
 [2] do_install(::WinRPM.Packages{Array{LibExpat.ETree,1}}) at C:\Users\ekim7\.julia\v0.6\WinRPM\src\WinRPM.jl:443
 [3] #install#21(::Bool, ::Function, ::WinRPM.Package) at C:\Users\ekim7\.julia\v0.6\WinRPM\src\WinRPM.jl:387
 [4] (::WinRPM.#kw##install)(::Array{Any,1}, ::WinRPM.#install, ::WinRPM.Package) at .\<missing>:0
 [5] install(::String) at C:\Users\ekim7\.julia\v0.6\WinRPM\src\WinRPM.jl:359

**Comment by musm** [comment]
Do you mind trying https://github.com/musm/WinRPM.jl to double check if it fixes this?

**Comment by eunjongkim** [comment]
@musm I have cloned your repository in my `Julia v0.5`. However, cloning your repository didn't fix my problem. When I search for the package I need, it results in an empty set.
```
julia> using WinRPM

julia> WinRPM.install("runtime")
ERROR: Package candidate for runtime not found
 in select(::WinRPM.Packages{Array{LibExpat.ETree,1}}, ::String) at C:\Users\ekim7\.julia\v0.5\WinRPM\src\WinRPM.jl:250
 in install(::String) at C:\Users\ekim7\.julia\v0.5\WinRPM\src\WinRPM.jl:363

julia> WinRPM.search("runtime")
WinRPM Package Set:
  <empty>
```

Did I do something wrong?

**Comment by musm** [comment]
first change directory to `Pkg.dir("WinRPM")`


```julia
git remote add musm https://github.com/musm/WinRPM.jl.git
git fetch musm
git checkout test
```

**Comment by eunjongkim** [comment]
@musm It's working fine with your suggestion. Thanks

**Comment by musm** [comment]
ok thanks I opened a PR here with the changes so hopefully soon you can go back to tagged version
