### ISSUE TITLE
Allow installation on non-compatible OSes

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPackaging/WinRPM.jl#151]
Given that Pkg3 doesn't support OS-specific dependencies (https://github.com/JuliaLang/Pkg.jl/issues/165), there needs to be a way to install this on incompatible OSes. The main problem is `deps/build.jl` (which is called at installation time) and attempts to call `WinRPM.update()`: could this be removed?

**Comment by tkelman** [comment]
It should work on non-rpm distros as well, theoretically. Has been used in the past to download the same windows cross-compiled libraries from Linux or Mac for testing purposes in wine or similar.

**Comment by simonbyrne** [comment]
Do we need to run update on installation?

**Comment by tkelman** [comment]
Can't remember what the need/justification for that is - but given the custom applications this has only ever been used for on non-Windows, making that particular step Windows-only by default should be fine.

**Comment by NHDaly** [comment]
Thanks for taking the initiative to fix this, Simon! :)
