### ISSUE TITLE
Drop HTTPClient.jl?

### ISSUE THREAD

**Issue by mcabbott** [JuliaPackaging/WinRPM.jl#176]
This package depends on HTTPClient.jl which is an archived repository, and implicitly bounds the package Compat.jl which causes problems elsewhere, discussed here https://github.com/JuliaRegistries/General/pull/8297 . 

Would it be easy to drop this in favour of HTTP.jl, as suggested there?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaPackaging/WinRPM.jl/pull/177
