### ISSUE TITLE
Pkg.add("WinRPM") error (WARNING: received error 0 while downloading)

### ISSUE THREAD

**Issue by zapazite** [JuliaPackaging/WinRPM.jl#27]
```
           _
```

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.0-prerelease+3841 (2014-06-22 11:24 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit b6ebf91 (2 days old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("WinRPM")
INFO: Installing BinDeps v0.2.14
INFO: Installing HTTPClient v0.1.4
INFO: Installing LibCURL v0.1.3
INFO: Installing LibExpat v0.0.4
INFO: Installing URIParser v0.0.2
INFO: Installing URLParse v0.0.0
INFO: Installing WinRPM v0.0.14
INFO: Installing Zlib v0.1.7
INFO: Building LibCURL
WARNING: skipping repodata/aee5879c2f6a0919d05907dcb04969d20a05c74c991513fce859b
6a0e9f675ef-primary.xml.gz, not in cache -- call WinRPM.update() to download
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/aee5879c2f6a0919d05907dcb04969d20a05c74c991513fce85
9b6a0e9f675ef-primary.xml.gz
WARNING: received error 0 while downloading http://download.opensuse.org/reposit
ories/windows:/mingw:/win32/openSUSE_Factory//repodata/aee5879c2f6a0919d05907dcb
04969d20a05c74c991513fce859b6a0e9f675ef-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win6
4/openSUSE_Factory//repodata/repomd.xml
INFO: Packages to install: libgpg-error-lang, libgpg-error, libgcc, libsqlite3-0
, libidn-lang, libgcrypt, libintl, libidn, mozilla-nss, zlib, mozilla-nspr, libs
sh2, libcurl
INFO: Downloading: libgpg-error-lang
INFO: try running WinRPM.update() and retrying the install
===============================[ ERROR: LibCURL ]===============================

failed to download libgpg-error-lang 0 from http://download.opensuse.org/reposit
ories/windows:/mingw:/win64/openSUSE_Factory//noarch/mingw64-libgpg-error-lang-1
.12-3.15.noarch.rpm.
while loading C:\Users\Maxime.julia\v0.3\LibCURL\deps\build.jl, in expression s
tarting on line 13
# 

================================[ BUILD ERRORS ]================================

WARNING: LibCURL had build errors.
- packages with build errors remain installed in C:\Users\Maxime.julia\v0.3
- build a package and all its dependencies with `Pkg.build(pkg)`
- build a single package by running its `deps/build.jl` script
# 

INFO: Package database updated

julia> WinRPM.update()
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win3
2/openSUSE_Factory//repodata/aee5879c2f6a0919d05907dcb04969d20a05c74c991513fce85
9b6a0e9f675ef-primary.xml.gz
WARNING: received error 0 while downloading http://download.opensuse.org/reposit
ories/windows:/mingw:/win32/openSUSE_Factory//repodata/aee5879c2f6a0919d05907dcb
04969d20a05c74c991513fce859b6a0e9f675ef-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win6
4/openSUSE_Factory//repodata/repomd.xml

julia> Version.i
ERROR: Version not defined

julia> Versioninfo()
ERROR: Versioninfo not defined

julia> versioninfo()
Julia Version 0.3.0-prerelease+3841
Commit b6ebf91 (2014-06-22 11:24 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

julia>

I have the same problem with julia 0.2

thanks for help

**Comment by DougFirErickson** [comment]
`WinRPM.__init__()` followed by `exit()` and then `using WinRPM` and `WinRPM.update()` before `Pkg.build("Cairo")` worked for me too!
