### ISSUE TITLE
WinRPM do not build in Julia 5.0

### ISSUE THREAD

**Issue by boonpingng** [JuliaPackaging/WinRPM.jl#96]
Hi,

I have this problem when building the package( Pkg.build("WinRPM") and using WinRPM.update().

Is there any problem with the source file?

julia> Pkg.build("WinRPM")
INFO: Building WinRPM
WARNING: Method definition XML_ErrorString(Any) in module LibExpat at C:\Users\bpng\JuliaPro-0.5.0.2
\pkgs-0.5.0.2\v0.5\LibExpat\src\lX_common_h.jl:4 overwritten at C:\Users\bpng\JuliaPro-0.5.0.2\pkgs-
0.5.0.2\v0.5\LibExpat\src\lX_common_h.jl:4.
WARNING: Method definition (::Type{WinRPM.Packages})(#T<:Union{Base.Set{LibExpat.ETree}, Array{LibEx
pat.ETree, 1}}) in module WinRPM at C:\Users\bpng\JuliaPro-0.5.0.2\pkgs-0.5.0.2\v0.5\WinRPM\src\WinR
PM.jl:207 overwritten at C:\Users\bpng\JuliaPro-0.5.0.2\pkgs-0.5.0.2\v0.5\WinRPM\src\WinRPM.jl:209.
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repo
data/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win32/open
SUSE_13.2/repodata/repomd.xml
(repeat until 5/5...)
WARNING: received error 0 while downloading http://download.opensuse.org/repositories/windows:/mingw
:/win64/openSUSE_13.2/repodata/repomd.xml

**Comment by nalimilan** [comment]
This is https://github.com/JuliaPackaging/WinRPM.jl/issues/57, closing in favor of it. Are you behind a proxy or with a special institutional configuration?
